### PR TITLE
Remove index pages from top level navigation

### PR DESCRIPTION
**Pull request by typaulhus**
Closes [GHI 484](https://github.com/cyberark/conjur/issues/484)

#### What does this pull request do?
Remove index pages from top level navigation

#### What background context can you provide?
Top nav links that should trigger dropdown are linking to un-needed index pages.

#### Where should the reviewer start?
Homepage.

#### How should this be manually tested?
Check that all top level nav items with dropdowns (currently all nav items) do not link to index pages, and instead only trigger dropdowns

#### Screenshots (if appropriate)
screen shot 2017-11-16 at 11 02 49 am

#### Link to build in Jenkins (if appropriate)
https://jenkins.conjur.net/job/cyberark--conjur/job/dropdown-fixes/

no

> Can we make a blog post, video, or animated GIF out of this?
no

> Is this explained in documentation?
no

> Does the knowledge base need an update?
no

### CODE REVIEW

**Comment by ryanprior** [comment]
A couple thoughts:

1. in the current design, the heading still have a finger pointer icon on mouseover, making it seem like they ought to link to something, but clicking does nothing. can we fix that?

2. as long as we're removing the links to these index pages, we ought to remove the files for those and make them redirects back to the main page.

**Comment by typaulhus** [comment]
@ryanprior @izgeri I added another commit that removes the top level index files, and changes the cursor to the default arrow instead of a finger for the dropdowns.

**Comment by izgeri** [comment]
@typaulhus I can look at this later if @ryanprior can't get to it today. Word to the wise - merge in master and add an entry to the CHANGELOG.md file following the standards laid out in README! I just forgot to do that on my PR :)

**Comment by jvanderhoof** [comment]
We don't need to make entries into the `CHANGELOG.md` file for non-functional changes to Conjur (like docs, conjur.org site).

**Comment by jvanderhoof** [comment]
With the move to a separate docs repo, this PR no longer makes sense.  We'll need to open this same set of changes against `cyberark/conjur-org`

**Pull request closed without merging**
