### PR TITLE
Add CodeClimate badge to README

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@sgnn7 I copied this from https://codeclimate.com/github/cyberark/conjur/badges#maintainability-markdown

Could you point me to the right id?

**Comment by sgnn7** [comment]
@gliptak I think you copied from the wrong repo (even the CC link out is wrong: `https://codeclimate.com/github/iterative/dvc/maintainability`) . The correct snippet is in my previous comment and you just need to copy/paste it.

**Comment by sgnn7** [comment]
Also, please ensure that your commits include the `--signoff` flag (https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s) to certify that you have the rights to submit the work under the same license as the project and you agree to a Developer Certificate of Origin (see http://developercertificate.org/ for more information).

**Comment by sgnn7** [comment]
@gliptak The more I'm thinking about this, if you feel like it feel like it, you can also add the test coverage badge too.

**Comment by gliptak** [comment]
@sgnn7 thank you for the pointers. I updated the PR

**Comment by sgnn7** [comment]
@gliptak Looks great! Thank you for your contribution!

**Pull request merged**
